### PR TITLE
correct degree features for adjectives

### PR DESCRIPTION
**Pull request by odanoburu**
considering what's actually found on the dictionary

### CODE REVIEW

**Comment by lluisp** [comment]
Hi Bruno, sorry for the delay in answering
These part of the manual is generated from the source data/pt/tagset.dat in freeling source.

I see that the dictionary contains these generated forms with tag AQC and AQD, but that is actually wrong, since FreeLing analyzes diminutives and augmentatives via the affixes module, not as dictionary entries.

The consistent way to cover these forms is to add new rules to affixes.dat.  Moreover, now affixes.dat marks evaluatives (either diminutives or superlatives) as "D" (the doc say "V" because it is copied from Spanish.

So, all this should be fixed in the code, and the documentation will update automatically.
- Remove diminuntives, augmentatives and superlatives from dictionary (both from AQ and for NC)
- Add rules to afixos.dat to generate those cases, and fix existing rules (that do not distinguish D and A)
- Fix tagset.dat to match the changes  (and make it consistent: e.g. since nouns are marked with A:augmentative; D:diminutive, adjectives should follow the same notation).

thanks!

**Comment by arademaker** [comment]
Hi @lluisp , this is a good point. Is there any good way already implemented to check for redundancies in the dictionary ? I mean forms that could be generated by the afixes + another dictionary form.

**Comment by arademaker** [comment]
I hope we can help with this issue in the next weeks

**Comment by lluisp** [comment]
The easy way to check is searching (e.g. with grep) for forms in the the dictionary with a tag that is not supposed to be there (e.g. AQC, AQD...)
After removing these, tou can also grep for forms with suffixes known to be diminutuves (-inha, -inho, etc). to check if there remain some forms that did not have the "D" or "A" tag.  Be careful not to remove forms with those suffixes that are not actual diminutives (e.g. meninho).

**Pull request closed without merging**
